### ISSUE TITLE
It would be nice if you would give this example some love

### ISSUE THREAD

**Issue by lemanschik** [andersevenrud/retro-css-shell-demo#6]
It would be nice if you could refactor to use the following pattern via js

```js
Object.assign(el.style, { color: "red" });
```

This will allow us to more easy load that as ESModule as also allow us later to do custom styling more easy the keyframe stuff can get simply a
```js
 createElement('style').innerText = `csss.......`
```

it would be nice when you also adapt that pattern in your osjs project it leads us as sayed to better reuse so we can work more easy together 

alternativ i would need to improve my stack and build chains more to run in the browser as also my resolve implementations and so on and so on

Wish you all the best love your projects.

**Comment by andersevenrud** [comment]
This is not really an example, and neither is it a library. So it was never made with customization in mind.

> some love

I'm afraid I've given this as much love as I can. I rarely have time to work on my side projects these days.

If you have a solution for this issue, feel free to submit a PR and we can work something out.
